name: Build omnisette-server

on:
  push:

jobs:
  build:
    name: Build omnisette-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install additional rust targets
        run: rustup target add i686-unknown-linux-musl

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross

      - name: Build for i686 without SIMD
        run: |
          cross build --release --target i686-unknown-linux-musl
          cp target/i686-unknown-linux-musl/release/omnisette-server target/omnisette-server-linux-i686-musl

      - name: Upload i686 without SIMD
        uses: actions/upload-artifact@v3.1.3
        with:
          name: omnisette-server-linux-aarch64-musl-no-simd
          path: target/omnisette-server-linux-i686-musl

      - name: Build with SIMD 
        run: rm .cargo/config.toml

      - name: Build for i686 with SIMD
        run: |
          cross build --release --target i686-unknown-linux-musl
          cp target/i686-unknown-linux-musl/release/omnisette-server target/omnisette-server-linux-i686-musl

      - name: Upload i686 with SIMD
        uses: actions/upload-artifact@v3.1.3
        with:
          name: omnisette-server-linux-aarch64-musl-simd
          path: target/omnisette-server-linux-i686-musl
